# Generated by Django 4.2.5 on 2023-10-05 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_ciudad', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id_competencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_competencia', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'competencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Debilidad',
            fields=[
                ('id_debilidad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_debilidad', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'debilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numeracion', models.IntegerField()),
                ('nombre_calle', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id_educacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('annio_inicio_educ', models.IntegerField()),
                ('annio_fin_educ', models.IntegerField()),
            ],
            options={
                'db_table': 'educacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id_experiencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cargo_empleo', models.CharField(db_comment='ejemplo: responsable de ventas', max_length=250)),
                ('nombre_empleo', models.CharField(max_length=250)),
                ('modo_trabajo', models.CharField(db_comment='Hibrido\nPresencial\nOnline', max_length=100)),
                ('fecha_inicio_exp', models.DateField()),
                ('fecha_termino_exp', models.DateField()),
                ('descripcion', models.BinaryField()),
            ],
            options={
                'db_table': 'experiencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id_formacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_formacion', models.CharField(db_comment='Basica completa\nMedia completa\nSuperior completa\n', max_length=250)),
            ],
            options={
                'db_table': 'formacion_academica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_formulario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_formulario', models.DateField()),
                ('pretencion_renta', models.IntegerField()),
                ('carta_recomendacion', models.BinaryField(blank=True, null=True)),
                ('info_adicional', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'formulario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id_habilidad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_habilidad', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'habilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_idioma', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'idioma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(max_length=250)),
                ('tipo_institucion', models.CharField(db_comment='Instituto\nUniversidad\nColegio\nLiceo\netc', max_length=250)),
            ],
            options={
                'db_table': 'institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogroAcademico',
            fields=[
                ('id_logro_academico', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_logro', models.CharField(max_length=250)),
                ('descripcion_logro', models.BinaryField()),
            ],
            options={
                'db_table': 'logro_academico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_oferta', models.CharField(max_length=250)),
                ('descripcion_oferta', models.BinaryField()),
                ('fecha_oferta', models.DateField()),
            ],
            options={
                'db_table': 'oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id_tipo_cargo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_cargo', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tipo_cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleo',
            fields=[
                ('id_tipo_empleo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_tipo_empleo', models.CharField(db_comment='Jornada completa\nJornada parcial\nAut¾nomo\nProfesional independiente\nContrato temporal\nContrato de prßcticas\nContrato de formaci¾n\nTemporal', max_length=250)),
            ],
            options={
                'db_table': 'tipo_empleo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_tipo_usuario', models.CharField(db_comment='USUARIO CLIENTE\nUSUARIO ADMINISTRADOR', max_length=250)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TituloProf',
            fields=[
                ('id_titulo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_titulo', models.CharField(max_length=250)),
                ('descripcion', models.BinaryField(blank=True, null=True)),
                ('pdf', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'titulo_prof',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut_usuario', models.IntegerField(blank=True, null=True)),
                ('dv_usuario', models.CharField(blank=True, max_length=1, null=True)),
                ('nombre', models.CharField(max_length=250)),
                ('segundo_nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('primer_apellido', models.CharField(max_length=250)),
                ('segundo_apellido', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=250)),
                ('telefono', models.IntegerField()),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('correo', models.CharField(max_length=200)),
                ('contrasenha', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompetenciaUsuario',
            fields=[
                ('pf_id_competencia', models.OneToOneField(db_column='pf_id_competencia', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.competencia')),
            ],
            options={
                'db_table': 'competencia_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebilidadUsuario',
            fields=[
                ('pf_id_debilidad', models.OneToOneField(db_column='pf_id_debilidad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.debilidad')),
            ],
            options={
                'db_table': 'debilidad_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HabilidadUsuario',
            fields=[
                ('pf_id_habilidad', models.OneToOneField(db_column='pf_id_habilidad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.habilidad')),
            ],
            options={
                'db_table': 'habilidad_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdiomaUsuario',
            fields=[
                ('pf_id_idioma', models.OneToOneField(db_column='pf_id_idioma', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.idioma')),
            ],
            options={
                'db_table': 'idioma_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioLogro',
            fields=[
                ('pf_id_usuario', models.OneToOneField(db_column='pf_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.usuario')),
            ],
            options={
                'db_table': 'usuario_logro',
                'managed': False,
            },
        ),
    ]
